use sakila;

-- List the number of films per category.
select category_id, count(film_id) from sakila.film_category
group by category_id;

-- Retrieve the store ID, city, and country for each store.

select sto.store_id, addr.address_id, addr.district, addr.city_id from sakila.address as addr
join sakila.store as sto
on addr.address_id = sto.address_id;

with city_store as (
select sto.store_id, addr.address_id, addr.district, addr.city_id from sakila.address as addr
join sakila.store as sto
on addr.address_id = sto.address_id
)
select store_id, s.address_id, s.city_id, c.city, c.country_id from city_store as s
join sakila.city as c
on s.city_id = c.city_id;

with country_store as (
with city_store as (
select sto.store_id, addr.address_id, addr.district, addr.city_id from sakila.address as addr
join sakila.store as sto
on addr.address_id = sto.address_id
)
select store_id, s.address_id, s.city_id, c.city, c.country_id from city_store as s
join sakila.city as c
on s.city_id = c.city_id
)
select ad.store_id, ad.city, con.country from country_store as ad
join sakila.country as con
on ad.country_id = con.country_id;

-- Calculate the total revenue generated by each store in dollars.

select sto.store_id, sta.staff_id from sakila.store as sto
join sakila.staff as sta
on sto.store_id = sta.store_id;

with staff_num as (
select sto.store_id, sta.staff_id from sakila.store as sto
join sakila.staff as sta
on sto.store_id = sta.store_id
)
select a.store_id, count(s.amount) as total_revenue from staff_num as a
join sakila.payment as s
on a.staff_id = s.staff_id
group by a.store_id;

-- Determine the average running time of films for each category.

select c.category_id, round(avg(length),2) as avg_running_time from sakila.film as f
join sakila.film_category as c
on f.film_id = c.film_id
group by category_id;

with average_time as (
select c.category_id, round(avg(length),2) as avg_running_time from sakila.film as f
join sakila.film_category as c
on f.film_id = c.film_id
group by category_id
)
select t.category_id, name, avg_running_time from sakila.category as cat
join average_time as t
on cat.category_id = t.category_id;